# Generated by Django 2.2.24 on 2021-08-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_topcompanies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopCompanies',
        ),
    ]
