# Generated by Django 2.2.24 on 2021-08-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_topcompanies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
