# Generated by Django 2.2.24 on 2021-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(upload_to='images/')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_url', models.TextField()),
            ],
        ),
    ]
