# Generated by Django 2.2.24 on 2021-08-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_category',
            name='cat_url',
            field=models.TextField(blank=True),
        ),
    ]
