# Generated by Django 2.2.24 on 2021-08-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('salary', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('jobdescription', models.TextField()),
                ('jobid', models.IntegerField()),
                ('jobview', models.IntegerField()),
                ('placeurl', models.TextField()),
                ('cat_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Job_Category')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Category')),
            ],
        ),
    ]
