# Generated by Django 2.2.24 on 2021-08-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_job_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='experience',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='jobview',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='placeurl',
            field=models.TextField(blank=True),
        ),
    ]
