# Generated by Django 2.2.24 on 2021-08-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_companies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
