# Generated by Django 2.2.24 on 2021-08-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
