# Generated by Django 2.2.24 on 2021-08-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
