# Generated by Django 2.2.24 on 2021-08-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_delete_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_categories',
            old_name='category',
            new_name='type',
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('jobtype', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('salary', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Category')),
            ],
        ),
    ]
