# Generated by Django 2.2.24 on 2021-08-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcategory_coursetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='coursetype',
        ),
    ]
