# Generated by Django 2.2.24 on 2021-08-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_coursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publis_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('simage', models.ImageField(upload_to='images/')),
                ('sbody', models.TextField()),
                ('url', models.TextField()),
                ('Relate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogCategory')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.CourseType')),
            ],
        ),
    ]
