# Generated by Django 2.2.24 on 2021-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
