# Generated by Django 2.2.24 on 2021-08-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210804_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
